spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eefy?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

    redis:
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true

springdoc:
  swagger-ui:
    path: swagger-ui
