server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://43.200.245.0:8761/eureka}

spring:
  application:
    name: gateway-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_MEMBER_URL}
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member/**, /api/auth/**
        - id: homework-service
          uri: lb://HOMEWORK-SERVICE
          predicates:
            - Path=/api/homework/**
        - id: study-class-service
          uri: lb://STUDY-CLASS-SERVICE
          predicates:
            - Path=/api/study-class/**

jwt:
  secret: ${SECRET_KEY}
