server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eefy_member?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member/**
        - id: homework-service
          uri: lb://HOMEWORK-SERVICE
          predicates:
            - Path=/api/homework/**
        - id: study-class-service
          uri: lb://STUDY-CLASS-SERTICE
          predicates:
            - Path=/api/study-class/**

jwt:
  secret: ${SECRET_KEY}
